reciprocity/zen-ui

- src/index.html
This PR is meant to test the CCI pipeline 🎩
> Added one option to the dropdown example

- src/components/zen-dropdown/test/zen-dropdown.spec.tsx
Updated tests to complete CCI pipeline
> Updated tests

- .storybook/manager.js
- .storybook/preview-head.html
- .storybook/preview.js
- package-lock.json
- package.json
- src/components/zen-dropdown/readme.md
- src/components/zen-dropdown/zen-dropdown.stories.ts
Component docs page is now flattened, so we have all stories and documentation on one page:
> Tweak component docs page

- .storybook/preview-head.html
- .storybook/preview.scss
- src/stories/Spacing.stories.mdx
- src/stories/utils/utils.js
- src/zen-styles/main.scss
- src/zen-styles/mixins/breakpoints.scss
- src/zen-styles/mixins/index.scss
- src/zen-styles/utilities/index.scss
- src/zen-styles/utilities/spacing.scss
- src/zen-styles/variables.scss
- webpack.config.js
Zen UI spacing utilities. Based on [Bootstrap](https://getbootstrap.com/docs/4.5/utilities/spacing/) but tailored to our needs.
> BAN-31: Spacing utilities

- src/components/zen-button/test/zen-button.spec.tsx
- src/components/zen-steps/zen-steps.scss
- src/components/zen-steps/zen-steps.spec.tsx
- src/zen-styles/mixins/helpers.scss
- src/zen-styles/mixins/index.scss
- src/zen-styles/variables.scss
[jira](https://reciprocitylabs.atlassian.net/browse/BAN-63)
> BAN-63: Components: Steps - Improvements

- src/components.d.ts
- src/components/zen-button/readme.md
- src/components/zen-button/test/zen-button.spec.tsx
- src/components/zen-button/zen-button.scss
- src/components/zen-button/zen-button.tsx
- src/components/zen-spinner/readme.md
- src/components/zen-spinner/test/zen-spinner.spec.tsx
- src/components/zen-spinner/zen-spinner.scss
- src/components/zen-spinner/zen-spinner.stories.ts
- src/components/zen-spinner/zen-spinner.tsx
- src/zen-styles/component-helpers.scss
- src/zen-styles/utilities/index.scss
- src/zen-styles/utilities/visibility.scss
- src/zen-styles/variables.scss
- yarn.lock
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-72)
> BAN-72: New spinner component

- src/components/zen-button/mixins.scss
- src/components/zen-button/zen-button.scss
- src/components/zen-dropdown/zen-dropdown.scss
- src/components/zen-spinner/zen-spinner.scss
- src/zen-styles/mixins/forms.scss
- src/zen-styles/normalize.scss
- src/zen-styles/variables.scss
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-78)
This PR also moved input mixins from zen-dropdown to mixins/forms
> BAN-78: Remove font sizes normalization

- src/components/zen-input-support-text/zen-input-support-text.scss
- src/components/zen-label/zen-label.scss
- src/components/zen-steps/zen-steps.scss
- src/stories/components/text-preview/text-with-details.scss
- src/zen-styles/mixins/forms.scss
- src/zen-styles/variables.scss
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-95)
> BAN-95: Fix text size vars

- src/components.d.ts
- src/components/zen-steps/readme.md
- src/components/zen-steps/types.tsx
- src/components/zen-steps/zen-steps.scss
- src/components/zen-steps/zen-steps.stories.ts
- src/components/zen-steps/zen-steps.tsx
- yarn.lock
See commits and [Jira](https://reciprocitylabs.atlassian.net/browse/BAN-87)
> BAN-87: Update zen-steps component with last design

- src/components.d.ts
- src/components/zen-dropdown/readme.md
- src/components/zen-dropdown/zen-dropdown.scss
- src/components/zen-dropdown/zen-dropdown.stories.ts
- src/components/zen-dropdown/zen-dropdown.tsx
Minor dropdown behaviour improvements
[jira](https://reciprocitylabs.atlassian.net/browse/BAN-77)
> BAN-77: Dropdown: Open upwards

- src/components.d.ts
- src/components/zen-dropdown/readme.md
- src/components/zen-dropdown/zen-dropdown.stories.ts
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-textarea/test/zen-textarea.spec.tsx
[jira](https://reciprocitylabs.atlassian.net/browse/BAN-76)
This one should be merged first:
https://github.com/reciprocity/zen-ui/pull/41
> BAN-76: Dropdown: Fix value prop

- .husky/pre-commit
- .husky/pre-push
- commitlint.config.js
- package.json
- yarn.lock
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-9)
- Added commitlint to Husky pre-commit hook
- Added pre-push hook so it runs linter, formater and tests before push
> BAN-9: Added commitlint to husky as pre-commit and created pre-push hook

- src/components.d.ts
- src/components/helpers/fa-icons.tsx
- src/components/helpers/helpers.ts
- src/components/helpers/types.ts
- src/components/zen-dropdown/readme.md
- src/components/zen-dropdown/zen-dropdown.scss
- src/components/zen-dropdown/zen-dropdown.stories.ts
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-input/zen-input.scss
- src/components/zen-textarea/zen-textarea.scss
- src/zen-styles/mixins/forms.scss
[jira](https://reciprocitylabs.atlassian.net/browse/BAN-113)
> BAN-113: Dropdown new props

- src/components.d.ts
- src/components/zen-input/readme.md
- src/components/zen-input/test/zen-input.spec.tsx
- src/components/zen-input/zen-input.scss
- src/components/zen-input/zen-input.stories.ts
- src/components/zen-input/zen-input.tsx
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-91)
> BAN-91: Zen input with slots

- package.json
- src/components.d.ts
- src/components/zen-button/zen-button.scss
- src/components/zen-dropdown/readme.md
- src/components/zen-menu-item/readme.md
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-124)
**Important:** Documentation lines added were missing from lasts PRs, they are autogenerated after run `yarn build` and they **need** to be in place.
> BAN-124: Removed min-width and added justify content center to button

- src/components/zen-button/zen-button.scss
- src/components/zen-button/zen-button.tsx
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-130)
> BAN-130: Prevent emit click event on disabled button

- src/components.d.ts
- src/components/zen-button/mixins.scss
- src/components/zen-button/readme.md
- src/components/zen-button/test/zen-button.spec.tsx
- src/components/zen-button/zen-button.scss
- src/components/zen-button/zen-button.stories.ts
- src/components/zen-button/zen-button.tsx
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-131)
> BAN-131: Remove native button implementation inside zen-button

- .storybook/helpers/argTypes.js
- README.md
- src/components.d.ts
- src/components/helpers/helpers.ts
- src/components/zen-dropdown/zen-dropdown.scss
- src/components/zen-dropdown/zen-dropdown.stories.mdx
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-menu-item/zen-option.scss
- src/components/zen-menu-item/zen-option.tsx
- src/stories/About.stories.mdx
- src/zen-styles/mixins/forms.scss
[jira](https://reciprocitylabs.atlassian.net/browse/BAN-132)
> BAN-132: Dropdown: Improvements

- .storybook/preview.scss
- src/components.d.ts
- src/components/helpers/helpers.ts
- src/components/helpers/types.ts
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-tooltip/zen-tooltip.scss
- src/components/zen-tooltip/zen-tooltip.stories.mdx
- src/components/zen-tooltip/zen-tooltip.tsx
- src/zen-styles/colors.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-139)
> BAN-139: Tooltip: Auto-position

- .storybook/preview.js
- .storybook/preview.scss
- README.md
- src/components/zen-input-support-text/zen-input-support-text.stories.ts
- src/components/zen-label/zen-label.stories.ts
- src/components/zen-menu-item/zen-option.stories.mdx
- src/stories/changelog.stories.mdx
- src/stories/developers.stories.mdx
- src/stories/getting_started.stories.mdx
- src/zen-styles/normalize.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-22)
> BAN-22: Add introduction story

- package.json
- src/stories/changelog.stories.mdx
- yarn.lock
Update changelog for npm release version 0.0.18
> Update changelog 0.0.18

- .storybook/helpers/argTypes.js
- src/components.d.ts
- src/components/zen-dropdown/zen-dropdown.stories.mdx
- src/stories/changelog.stories.mdx
- src/stories/components/docs-table/docs-table.scss
- src/stories/components/docs-table/docs-table.tsx
- src/stories/components/docs-table/readme.md
- yarn.lock
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-146)
> BAN-146: Storybook: Custom docs (events, methods,...) table

- src/stories/Typography.stories.mdx
- src/stories/components/text-preview/text-with-details.scss
- src/stories/components/text-preview/text-with-details.tsx
- src/zen-styles/typography.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-147)
> BAN-147: Fix Typography story

- .storybook/preview.scss
- src/components.d.ts
- src/components/zen-dropdown/zen-dropdown.stories.mdx
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-tooltip/zen-tooltip.scss
- src/components/zen-tooltip/zen-tooltip.stories.mdx
- src/components/zen-tooltip/zen-tooltip.tsx
- src/stories/changelog.stories.mdx
- src/stories/components/docs-table/docs-table.tsx
- src/stories/components/docs-table/readme.md
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-148)
**Note!**
The First 3 commits belong to this PR, but weren't pushed:
https://github.com/reciprocity/zen-ui/pull/76
> BAN-148: Fix: Tooltip and Dropdown

- .husky/pre-push
- babel.config.json
- package.json
- src/components/zen-tooltip/test/zen-tooltip.spec.tsx
- src/stories/getting_started.stories.mdx
- stencil.config.ts
- tsconfig.json
- yarn.lock
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-142)
> BAN-142: Bringed tests back running transforms with babel-jest

- .storybook/preview.js
- src/components.d.ts
- src/stories/components/html-playground/helpers.ts
- src/stories/components/html-playground/html-playground.scss
- src/stories/components/html-playground/html-playground.tsx
- src/stories/components/html-playground/readme.md
- src/stories/playground.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-154)
> BAN-154: Create playground component and story for it

- .circleci/config.yml
- README.md
- package.json
- yarn.lock
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-158)
PR adds test coverage badge.
> BAN-158: Add test coverage badge

- .gitignore
- .husky/pre-push
- cypress.json
- cypress/constants.js
- cypress/integration/html-playground.e2e.js
- cypress/utils.js
- package.json
PR does some clean up from the [POC PR](https://github.com/reciprocity/zen-ui/pull/86) and adds mandatory e2e tests checks to pre-push hook.
> QUICK-FIX: Clean up E2E tests

- .husky/pre-push
> QUICK-FIX: Remove running E2E tests in pre-push hook

- .eslintrc.js
- cypress/.eslintrc.js
- cypress/integration/html-playground.e2e.js
- package.json
- tsconfig.json
- yarn.lock
I have added the cypress plugins for the eslint.
> Add eslint support for cypress

- cypress/support/index.d.ts
- tsconfig.json
I have added the index.d.ts file so we can write a description for all our custom commands and when we decide to switch to typescript we can do it easily and also this description help us today also.
> Add typescript support for cypress

- .circleci/config.yml
- package.json
- yarn.lock
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-818)
PR adds job to CI for running VRTs.
Supersedes https://github.com/reciprocity/zen-ui/pull/90.
> PLAT-818: Run visual regression tests on CI

- README.md
- docs/testing.md
- package.json
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-827)
PR adds documentation for testing.
> PLAT-827: Add testing docs

- docs/testing.md
PR fixe some typos in the testing doc.
> QUICK-FIX: Fix typos in testing doc

- .storybook/manager.js
- .storybook/preview.js
- src/components.d.ts
- src/components/helpers/jest.ts
- src/components/zen-button/test/zen-button.spec.tsx
- src/components/zen-button/zen-button.scss
- src/components/zen-button/zen-button.stories.ts
- src/components/zen-button/zen-button.tsx
- src/components/zen-checkbox/test/zen-checkbox.spec.tsx
- src/components/zen-checkbox/zen-checkbox.stories.ts
- src/components/zen-checkbox/zen-checkbox.tsx
- src/components/zen-dropdown/zen-dropdown.stories.mdx
- src/components/zen-label/zen-label.stories.ts
- src/components/zen-menu-item/zen-option.stories.mdx
- src/components/zen-spinner/zen-spinner.scss
- src/components/zen-spinner/zen-spinner.stories.ts
- src/components/zen-spinner/zen-spinner.tsx
- src/components/zen-steps/types.tsx
- src/components/zen-steps/zen-steps.spec.tsx
- src/components/zen-steps/zen-steps.stories.ts
- src/components/zen-steps/zen-steps.tsx
- src/stories/changelog.stories.mdx
- src/stories/components/docs-table/docs-table.tsx
Check out commit messages for what has been changed.
> Small fixes

- .github/workflows/visual-testing.yml
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-841)
Simple stuff. Turns out not so simple to implement. 😅
> PLAT-841: Add comment to PR for visual testing snapshot changes

- .github/workflows/visual-testing.yml
> QUICK-FIX: Fix PR comment for displaying multiple files in list

- .storybook/helpers/custom-action.js
- docs/components-guidelines.md
- src/components.d.ts
- src/components/zen-checkbox/types.ts
- src/components/zen-checkbox/zen-checkbox.stories.mdx
- src/components/zen-checkbox/zen-checkbox.tsx
- src/components/zen-dropdown/zen-dropdown.stories.mdx
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-input/zen-input.stories.mdx
- src/components/zen-input/zen-input.tsx
- src/components/zen-steps/zen-steps.stories.mdx
- src/components/zen-steps/zen-steps.tsx
- src/components/zen-textarea/zen-textarea.stories.mdx
- src/components/zen-textarea/zen-textarea.tsx
- src/stories/changelog.stories.mdx
- src/stories/components/docs-table/docs-table.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-835)
> PLAT-835: Emmit Native Events

- src/componentTemplate.stories.mdx.sample
- src/components/zen-button/test/zen-button.spec.tsx
- src/components/zen-button/zen-button.stories.mdx
- src/components/zen-button/zen-button.tsx
- src/components/zen-checkbox/zen-checkbox.stories.mdx
- src/components/zen-dropdown/zen-dropdown.stories.mdx
- src/components/zen-input-support-text/zen-input-support-text.stories.mdx
- src/components/zen-input/zen-input.stories.mdx
- src/components/zen-label/zen-label.stories.mdx
- src/components/zen-menu-item/zen-option.stories.mdx
- src/components/zen-steps/zen-steps.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-839)
> PLAT-839: Fix small glitches

- README.md
> QUICK-FIX: Fix command in readme

- src/components/zen-button/test/zen-button.spec.tsx
- src/components/zen-checkbox/test/zen-checkbox.spec.tsx
- src/components/zen-input-support-text/test/zen-input-support-text.spec.tsx
- src/components/zen-input/test/zen-input.spec.tsx
- src/components/zen-input/zen-input.tsx
- src/components/zen-label/test/zen-label.spec.tsx
- src/components/zen-spinner/test/zen-spinner.spec.tsx
- src/components/zen-textarea/test/zen-textarea.spec.tsx
- src/components/zen-textarea/zen-textarea.tsx
Updated tests for:
- input
- checkbox
- button
- textarea
- spinner
- label
- support text
[JIRA Ticket - Fix existing tests](https://reciprocitylabs.atlassian.net/browse/BAN-164)
[JIRA Ticket - Improve incomplete tests](https://reciprocitylabs.atlassian.net/browse/BAN-165)
> BAN-164: Fix existing and improve incomplete tests

- package.json
- src/components/helpers/helpers.ts
- src/components/helpers/jest.ts
- src/components/zen-animate/test/zen-animate.spec.tsx
- src/components/zen-animate/zen-animate.tsx
- src/components/zen-dropdown/test/zen-dropdown.spec.tsx
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-input/zen-input.tsx
- src/components/zen-menu-item/test/zen-option.spec.tsx
- src/components/zen-tabs/test/zen-tabs.spec.tsx
- src/stories/components/html-playground/html-playground.tsx
- yarn.lock
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-166)
> BAN-166: Write component tests

- docs/components-guidelines.md
Add instructions on how to create visual regression tests for newly added components.
> QUICKFIX: Update docs - VRT for new component

- cypress.json
This will enable us to avoid failure when the environment is unstable.
> Add retry to the tests

- src/components.d.ts
- src/components/zen-table-cell/zen-table-cell.tsx
- src/components/zen-table-header-cell/test/zen-table-header-cell.spec.tsx
- src/components/zen-table-header-cell/zen-table-header-cell.scss
- src/components/zen-table-header-cell/zen-table-header-cell.tsx
- src/components/zen-table-header/test/zen-table-header.spec.tsx
- src/components/zen-table-header/zen-table-header.scss
- src/components/zen-table-header/zen-table-header.tsx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table.scss
- src/components/zen-table/zen-table.stories.mdx
- src/components/zen-table/zen-table.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1004)
PR adds sticky header support to ZenTable.
> PLAT-1004: ZenTable sticky header

- src/components/zen-table-cell/test/zen-table-cell.spec.tsx
- src/components/zen-table-header-cell/test/zen-table-header-cell.spec.tsx
- src/components/zen-table-header/test/zen-table-header.spec.tsx
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table/test/zen-table.spec.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1013)
Some simple unit tests for these components since there's not much else to test yet.
> PLAT-1013: ZenTable unit tests

- src/components/zen-table-cell/test/zen-table-cell.spec.tsx
- src/components/zen-table-header-cell/test/zen-table-header-cell.spec.tsx
- src/components/zen-table-header/test/zen-table-header.spec.tsx
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table/test/zen-table.spec.tsx
Uni test fixes per [this comment](https://github.com/reciprocity/zen-ui/pull/130#discussion_r566213888) on PR https://github.com/reciprocity/zen-ui/pull/130
> FIX: Change ZenTable unit tests to not rely on snapshot testing

- src/components/zen-tooltip/zen-tooltip.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1154)
> PLAT-1154: Fix slot content width in firefox

- src/componets-smart/zen-avatar-group/test/zen-avatar-group.spec.tsx
- src/componets-smart/zen-avatar-group/zen-avatar-group.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1168)
Fixed the issue. Regarding seperation to another folder was suggested by you guys. :) I think this is not a smart one and i can move it under the components folder, just that we decide.
> PLAT-1168: Fix avatar group max display issue

- src/components/zen-progress-tracker/zen-progress-tracker.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1159)
> PLAT-1159: Fix for progress tracker

- src/zen-styles/shadows.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1200)
> PLAT-1200: Unify shadows: Add variables

- src/components.d.ts
- src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx
- src/components/zen-avatar-group/zen-avatar-group.stories.mdx
- src/components/zen-avatar-group/zen-avatar-group.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1195)
> PLAT-1195: Fix number of avatar icons

- .eslintrc.js
- cypress/.eslintrc.js
- src/.eslintrc.js
Quick fix for issue mentioned here: https://github.com/reciprocity/zen-ui/pull/170
> QUICKFIX: ESLint config cascading

- src/components/zen-menu-item/zen-option.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1139)
> PLAT-1139: Dropdown option - Hover style is ON when 'focused' or 'selected' are set to true even 'noHover' is set to true

- src/components/zen-menu-item/zen-option.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1109)
> PLAT-1109: FF - 'focus' and 'selected' doesn't work for dropdown

- docs/components-guidelines.md
- docs/contributing.md
- package.json
- src/stories/changelog.stories.mdx
- yarn.lock
Updated contributing docs as well as docs for version 1.0.1 bump.
> QUICK: Docs update and v1.0.1 changelog

- src/components.d.ts
- src/components/zen-button/zen-button.tsx
- src/components/zen-checkbox/zen-checkbox.tsx
- src/components/zen-input/zen-input.tsx
- src/components/zen-radio/zen-radio.tsx
- src/components/zen-textarea/zen-textarea.tsx
- src/components/zen-toggle/zen-toggle.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1276)
> PLAT-1276: form components - add prop "name"

- src/components.d.ts
- src/components/helpers/types.ts
- src/components/zen-popover/test/zen-popover.spec.tsx
- src/components/zen-popover/zen-popover.scss
- src/components/zen-popover/zen-popover.stories.mdx
- src/components/zen-popover/zen-popover.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1273)
- Also checked that events are fired only once.
- Added also check that on hover when mouse is moving it dosent execute the show popper a milion times.
> PLAT-1273: Add trigger events

- package.json
- src/components.d.ts
- src/components/zen-date-picker/date-helpers.tsx
- src/components/zen-date-picker/zen-date-picker.scss
- src/components/zen-date-picker/zen-date-picker.tsx
- yarn.lock
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1267)
> PLAT-1267: Date picker - Implement months/years switching

- src/components/zen-date-picker/zen-date-picker.stories.mdx
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-popover/zen-popover.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1288)
> PLAT-1288: Fix popover and calendar tag prefix

- src/components.d.ts
- src/components/zen-date-picker/zen-date-picker.scss
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-popover/test/zen-popover.spec.tsx
- src/components/zen-popover/zen-popover.scss
- src/components/zen-popover/zen-popover.stories.mdx
- src/components/zen-popover/zen-popover.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1274)
> PLAT-1274: Popover - Add prop visible and delays

- src/components.d.ts
- src/components/helpers/animations.ts
- src/components/zen-animate/test/zen-animate.spec.tsx
- src/components/zen-popover/animations.scss
- src/components/zen-popover/zen-popover.scss
- src/components/zen-popover/zen-popover.stories.mdx
- src/components/zen-popover/zen-popover.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1312)
Tests will be addressed in different tickets:
https://reciprocitylabs.atlassian.net/browse/PLAT-1313
https://reciprocitylabs.atlassian.net/browse/PLAT-1312
> PLAT-1312: Popover: Add animations

- src/components/zen-tooltip/zen-tooltip.scss
- src/components/zen-tooltip/zen-tooltip.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1290)
> PLAT-1290: Fix text color in tooltip story

- src/components/zen-notification/test/zen-notification.spec.tsx
- src/components/zen-notification/zen-notification.scss
- src/components/zen-notification/zen-notification.stories.mdx
- src/components/zen-notification/zen-notification.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1329)
@f-jauregui 
1. Should we add visible param?
2. Should we remove dismiss after timeout functionality? Is this being handled in notifications stack?
> PLAT-1329: Fix notification icons

- src/components.d.ts
- src/components/zen-drawer/zen-drawer.stories.mdx
- src/components/zen-drawer/zen-drawer.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1336)
@chavlji Should i add also on click outside close event listener. I soo this was also in requirements.
> PLAT-1336: Add emit on close click event

- src/components/helpers/animations.ts
- src/components/helpers/helpers.ts
- src/components/helpers/tests/animations.spec.tsx
- src/components/helpers/tests/helpers.spec.tsx
- src/components/zen-popover/test/zen-popover.spec.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1331)
> PLAT-1331: Popover - Add unit test

- src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-input/zen-input.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1284)
> PLAT-1284: Date picker - Add unit tests

- package.json
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1334)
> PLAT-1334: Moved lit helpers to dev dependencies

- src/components.d.ts
- src/components/zen-dropdown/test/zen-dropdown.spec.tsx
- src/components/zen-dropdown/zen-dropdown.scss
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-popover/animations.scss
- src/components/zen-popover/zen-popover.scss
- src/components/zen-popover/zen-popover.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1348)
> PLAT-1348: Dropdown - Rebase to popover

- cypress/integration/visual/notification.e2e.js
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1420)
> PLAT-1420: Slow down notifications test

- src/components.d.ts
- src/components/helpers/helpers.ts
- src/components/zen-dropdown/test/zen-dropdown.spec.tsx
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-menu-item/zen-option.scss
- src/components/zen-popover/zen-popover.scss
- src/components/zen-popover/zen-popover.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1389)
> PLAT-1389: Dropdown - Scroll on keyboard selection

- src/components.d.ts
- src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
- src/components/zen-date-picker/zen-date-picker.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1357)
> PLAT-1357: Default value for date format is not applied to the date picker

- src/components.d.ts
- src/components/helpers/types.ts
- src/components/zen-textarea/zen-textarea.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1426)
> PLAT-1426: Add resize, row, cols properties

- .storybook/preview.scss
- package.json
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1485)
> PLAT-1485: Firefox: Some stories are broken

- src/components/zen-progress-tracker/zen-progress-tracker.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1159)
> PLAT-1159: Change that active index control is number

- .husky/pre-commit
Removing lint on commit because of error that's preventing us doing any commits:
> QUICK: Remove lint on commit

- src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-dropdown/test/zen-dropdown.spec.tsx
- src/components/zen-dropdown/zen-dropdown.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1495)
> PLAT-1495: Dropdown receives focus but doesn't open

- src/components/zen-input/zen-input.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1494)
✅ This also covers the fix for [PLAT-889](https://reciprocitylabs.atlassian.net/browse/PLAT-899)
> PLAT-1494: Date picker width now can be changed

- cypress/integration/visual/date-picker.e2e.js
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1543)
The test is working great no need for any changes.
> PLAT-1543: Remove duplicated variable

- .storybook/helpers/argTypes.js
- src/components.d.ts
- src/components/helpers/helpers.scss
- src/components/helpers/helpers.ts
- src/components/helpers/tests/helpers.spec.tsx
- src/components/zen-space/zen-space.scss
- src/components/zen-space/zen-space.tsx
- src/stories/changelog.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1629)
> PLAT-1629: Add margin props to zen-space

- src/components.d.ts
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-input/test/zen-input.spec.tsx
- src/components/zen-input/zen-input.scss
- src/components/zen-input/zen-input.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1610)
> PLAT-1610: zen-input: add clear button

- src/components.d.ts
- src/components/zen-date-picker/zen-date-picker.scss
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-dropdown/zen-dropdown.scss
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-textarea/zen-textarea.scss
- src/components/zen-textarea/zen-textarea.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1557)
> PLAT-1557: Form components invalid state

- src/components.d.ts
- src/components/zen-table-header/zen-table-header.stories.mdx
- src/components/zen-table-header/zen-table-header.tsx
- src/components/zen-table-row/zen-table-row.stories.mdx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table.stories.mdx
- src/components/zen-table/zen-table.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1541)
- Moved row selected logic from table to row watch selected
- Moved row expanded logic from table to row watch selected
- Moved table header select logic to header watch selected
- Cleaned up the components code and added descriptions
> PLAT-1541: Add  properties watch

- cypress/integration/visual/tooltip.e2e.js
- src/components.d.ts
- src/components/zen-tooltip/test/zen-tooltip.spec.tsx
- src/components/zen-tooltip/zen-tooltip.scss
- src/components/zen-tooltip/zen-tooltip.stories.mdx
- src/components/zen-tooltip/zen-tooltip.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1605)
> PLAT-1605: Add title and hyperlink to tooltip

- src/components/zen-toggle/zen-toggle.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1612)
> PLAT-1612: Updated zen-toggle styles

- docs/contributing.md
- docs/conventional-commits.md
No ticket, just check the docs and see if it makes sense; I copied the one I showed you today and modified some parts :P.
> QUICK: Add documentation about conventional commits

- src/components.d.ts
- src/components/zen-table-header-cell/zen-table-header-cell.tsx
- src/components/zen-table-header/test/zen-table-header.spec.tsx
- src/components/zen-table-header/zen-table-header.tsx
- src/components/zen-table-row/test/zen-table-row.spec.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1537)
Probably could test much more and code could be simplified. But have to get some more experience writing them. 
> PLAT-1537: Add unit test for table header and row

- src/components.d.ts
- src/components/zen-textarea/zen-textarea.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1696)
> PLAT-1696: Added focusInput method to zen-textarea

- src/components/zen-avatar-details/zen-avatar-details.scss
- src/components/zen-avatar-details/zen-avatar-details.tsx
- src/components/zen-avatar-group/zen-avatar-group.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1678)
> PLAT-1678: Fix avatar group wrap issue

- src/components/zen-drawer/zen-drawer.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1733)
> PLAT-1733: Fix drawer element still exists on hide

- cypress/integration/visual/avatarGroup.e2e.js
- src/components.d.ts
- src/components/helpers/types.ts
- src/components/zen-avatar-details/zen-avatar-details.tsx
- src/components/zen-avatar-group/zen-avatar-group.stories.mdx
- src/components/zen-avatar-icon/zen-avatar-icon.tsx
- src/components/zen-avatar/zen-avatar.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1772)
- Tried all the different regex expressions (also suggested ones) and could not make it work. :(
- Added override option for initials to all needed components.
> PLAT-1772: Fix for initials not displayed correctly

- src/components.d.ts
- src/components/zen-tabs/zen-tabs.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1816)
> PLAT-1816: Fix that tabs stretch full width

- src/components/zen-progress-tracker/zen-progress-tracker.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1805)
> PLAT-1805: Progress tracker labels now have white-space nowrap style

- src/components.d.ts
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table-helpers.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1798)
2st part of ticket [PLAT-1667: Table: indeterminate state inconsistent](https://reciprocitylabs.atlassian.net/browse/PLAT-1667)
> PLAT-1798: Table: Move header updating to zen-table.tsx

- .storybook/helpers/argTypes.js
- .storybook/preview.scss
- cypress/integration/visual/avatarGroup.e2e.js
- docs/components-guidelines.md
- src/stories/components/docs-table/docs-table.tsx
Duplicate of https://github.com/reciprocity/zen-ui/pull/309 to merge in master
> PLAT-1735: Storybook: Mark $props as readonly in props table - Merge to MASTER

- src/components.d.ts
- src/components/zen-table-cell/zen-table-cell.scss
- src/components/zen-table-cell/zen-table-cell.stories.mdx
- src/components/zen-table-cell/zen-table-cell.tsx
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table-row/zen-table-row.stories.mdx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table-helpers.tsx
- src/components/zen-table/zen-table.stories.mdx
- src/components/zen-table/zen-table.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1799)
3rd part of ticket [PLAT-1667: Table: indeterminate state inconsistent](https://reciprocitylabs.atlassian.net/browse/PLAT-1667)
**!WARNING!**
Based on https://github.com/reciprocity/zen-ui/pull/309! It should be merged first!
> PLAT-1799: Table: Make private props readonly

- src/components/zen-menu-item/zen-option.scss
- src/components/zen-menu-item/zen-option.tsx
⚠️ Not sure I totally understood the issue in this ticket but let's see if this solve it.
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1691)
> PLAT-1691: Updated zen-option mouseover hover style and remove keyboard focused style when mouseover

- src/components/helpers/jest.ts
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/test/zen-table.spec.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1794)
> PLAT-1794: Test: Fix zen-table tests errors

- src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-input/zen-input.tsx
⚠️ **NOTE: Nor onClick and onMouseup worked on this component, not sure if it's a Stencil bug.** ⚠️ 
> PLAT-1773: When clear button is clicked on zen-input a change event is triggered

- src/components/zen-tabs/zen-tabs.scss
- src/components/zen-tabs/zen-tabs.stories.mdx
- src/components/zen-tabs/zen-tabs.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1917)
> PLAT-1917: Quick fix for tabs issues

- src/components.d.ts
- src/components/zen-table/zen-table.tsx
> QUICK-FIX: add table column type

- src/components.d.ts
- src/components/scss/vars/colors.scss
- src/components/zen-sidebar/zen-sidebar.scss
- src/components/zen-sidebar/zen-sidebar.stories.mdx
- src/components/zen-sidebar/zen-sidebar.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1987)
> PLAT-1987: Create zen-sidebar component

- .storybook/helpers/utils.js
- src/components.d.ts
- src/components/scss/vars/colors.scss
- src/components/zen-sidebar-nav/zen-sidebar-nav.scss
- src/components/zen-sidebar-nav/zen-sidebar-nav.stories.mdx
- src/components/zen-sidebar-nav/zen-sidebar-nav.tsx
- src/components/zen-sidebar/zen-sidebar.scss
- src/components/zen-sidebar/zen-sidebar.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1992)
Based on https://github.com/reciprocity/zen-ui/pull/332
> PLAT-1992: Create zen-sidebar-nav component

- src/components.d.ts
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.scss
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.stories.mdx
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.tsx
- src/components/zen-sidebar-nav/zen-sidebar-nav.stories.mdx
- src/components/zen-sidebar-nav/zen-sidebar-nav.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1993)
Bsed on https://github.com/reciprocity/zen-ui/pull/333
> PLAT-1993: Create zen-sidebar-nav-item component

- src/components.d.ts
- src/components/helpers/helpers.ts
- src/components/scss/vars/colors.scss
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.scss
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.tsx
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.scss
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.stories.mdx
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.tsx
- src/components/zen-sidebar-nav/zen-sidebar-nav.scss
- src/components/zen-sidebar-nav/zen-sidebar-nav.stories.mdx
- src/components/zen-sidebar-nav/zen-sidebar-nav.tsx
- src/components/zen-sidebar/zen-sidebar.scss
- src/components/zen-sidebar/zen-sidebar.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1994)
Based on https://github.com/reciprocity/zen-ui/pull/334
> PLAT-1994: Create zen-sidebar-nav-subitem component

- .storybook/helpers/utils.js
- src/components.d.ts
- src/components/helpers/helpers.ts
- src/components/scss/vars/colors.scss
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.scss
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.stories.mdx
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.tsx
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.scss
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.stories.mdx
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.tsx
- src/components/zen-sidebar-nav/zen-sidebar-nav.scss
- src/components/zen-sidebar-nav/zen-sidebar-nav.stories.mdx
- src/components/zen-sidebar-nav/zen-sidebar-nav.tsx
- src/components/zen-sidebar/zen-sidebar.scss
- src/components/zen-sidebar/zen-sidebar.stories.mdx
- src/components/zen-sidebar/zen-sidebar.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-842)
This PR is a feature branch of the following PRs:
- #332 Create zen-sidebar component 
- #333 Create zen-sidebar-nav component 
- #334 Create zen-sidebar-nav-item component 
- #335 Create zen-sidebar-nav-subitem component 
> PLAT-842: Navigation Menu Component

- src/components/zen-table/zen-table.tsx
- test if observer was even created before trying to disconnect it
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2105)
> PLAT-2105: Fix errors triggered when the table gets unmounted

- src/components/zen-checkbox/zen-checkbox.scss
- src/components/zen-checkbox/zen-checkbox.tsx
Instead of embedding svg, we should just use zen-icon as with all
other components.
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2179)
> PLAT-2179: [zen-ui] Checkbox indeterminate state is broken

- src/components.d.ts
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2228)
> PLAT-2228: Table row events not sent

- src/components/zen-tab/zen-tab.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2243)
> PLAT-2243: Fix apply styles on params like string

- src/components.d.ts
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.scss
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.tsx
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.scss
- src/components/zen-sidebar-nav-subitem/zen-sidebar-nav-subitem.tsx
- src/components/zen-sidebar-nav/zen-sidebar-nav.stories.mdx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2242)
> PLAT-2242: Zen-UI: Add disabled prop to zen-sidebar-nav-item

- package.json
- src/components/zen-table-cell/zen-table-cell.tsx
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table.tsx
- yarn.lock
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2264)
> PLAT-2264 - Fix jumping behavior the table

- src/components/scss/vars/shadows.scss
- src/components/zen-card/zen-card.scss
- src/components/zen-drawer/zen-drawer.scss
- src/components/zen-modal/zen-modal.scss
- src/components/zen-notification/zen-notification.scss
- src/components/zen-popover/zen-popover.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2026)
⚠️ Check with designs: https://www.figma.com/file/rWXEQiJcBXbkMY8V4NSM1d/ZenGRC-Component-Library?node-id=1463%3A13
> PLAT-2026: New shadow styles

- src/components/zen-table-row/zen-table-row.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2237)
> PLAT-2237: When on slow network on refresh we get an error on the table component

- src/components.d.ts
- src/components/zen-avatar-icon/zen-avatar-icon.tsx
- src/components/zen-menu-item/zen-option.tsx
- src/components/zen-menu/test/zen-menu.spec.tsx
- src/components/zen-menu/zen-menu.scss
- src/components/zen-menu/zen-menu.stories.mdx
- src/components/zen-menu/zen-menu.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-967)
> PLAT-967: Add menu component

- src/components.d.ts
- src/components/zen-checkbox/zen-checkbox.tsx
- src/components/zen-table-cell/zen-table-cell.tsx
- src/components/zen-table-row/zen-table-row.stories.mdx
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2401)
> PLAT-2401: Improve bulk-select events on zen-table

- .circleci/config.yml
- src/components/zen-space/zen-space.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2405)
> PLAT-2405: Remove `zen-space` `should not be empty` text

- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-icon/zen-icon.tsx
- src/components/zen-input/zen-input.tsx
- src/components/zen-popover/zen-popover.tsx
- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.tsx
- src/components/zen-skeleton/zen-skeleton.tsx
- src/components/zen-sortable/zen-sortable.tsx
- src/components/zen-space/zen-space.tsx
- src/components/zen-status-tracker/zen-status-tracker.tsx
- src/components/zen-tab/zen-tab.scss
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table.tsx
- src/components/zen-tabs/zen-tabs.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2263)
https://github.com/reciprocity/zen-ui/pull/361 needs to be merged first!
> PLAT-2263: Fix jumping behavior on all components except the table

- src/components.d.ts
- src/components/zen-tab/test/zen-tab.spec.tsx
- src/components/zen-tab/zen-tab.scss
- src/components/zen-tab/zen-tab.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2372)
> PLAT-2372: [zen-ui] Remove badge from tab component

- src/components/zen-popover/zen-popover.scss
> QUICK: zen-popover - break long words

- .storybook/helpers/argTypes.js
- src/components.d.ts
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-popover/zen-popover.tsx
Adding new prop to popover that will enable us to wait with popover render until popover is rendered.
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2527)
> PLAT-2547: [mf-execution] Research performance issues on table
