reciprocity/zen-ui

- .storybook/preview.scss
- src/stories/Flex.stories.mdx
- src/stories/Spacing.stories.mdx
- src/stories/utils/utils.js
- src/zen-styles/utilities/flex.scss
- src/zen-styles/utilities/index.scss
Added flex utility classes.
I've also imported `utilities/index.scss` to Storybook, so we can use all utility classes on Storybook design directly. For now, I'd avoid importing the whole `zen-ui-styles` into the Storybook.
> BAN-32: Flex utils

- package.json
- yarn.lock
Due to:
Added https://github.com/typicode/pinst to prevent postinstall (husky) from run when package is consumed.
> QUICKFIX: Added pinst and updated package version

- package.json
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-notification/test/zen-notification.spec.tsx
- src/components/zen-notification/zen-notification-helper.ts
- src/components/zen-notification/zen-notification.tsx
- src/components/zen-steps/zen-steps.tsx
- yarn.lock
Fixed:
- Lodash was bloating our build adding more than 17k lines to the custom elements index.
- Missing types that throw errors on lint.
> quickfix: cleaned all lint errors and corrected lodash imports

- .github/pull_request_template.md
Add pull request template file. [JIRA](https://reciprocitylabs.atlassian.net/browse/BAN-29)
1. Probably we should have a separate repo for general documentation. Or we add a doc polder to our own? For now i left useful links to point to old ZenGrc repo.
2. The Ticket code should be pulled automatically from the branch name by the jira specification. It issent so it seams like a bug to me. Will check more in depth in a next ticket if this dosent get fixed in some time.
3. Will update change log file link when we have autogenerated change logs. :)
> BAN-29: Add pull request template

- src/components/zen-dropdown/zen-dropdown.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-617)
https://user-images.githubusercontent.com/48444599/106124948-68d94900-613a-11eb-9799-b43b1d0fc444.mov
> PLAT-617: Removed bottom padding that overlaps other components when dropdown is closed

- .storybook/helpers/utils.js
- src/components/zen-steps/zen-steps.stories.mdx
Helper function waitForElement should be used inside stories to do some js after story has been rendered.
Such as appending /array props to web components. Eg. `document.querySelector('#steps').steps = args.steps`
> QUICKFIX: Add waitForElement helper function

- .storybook/helpers/argTypes.js
- src/componentTemplate.stories.mdx.sample
- src/components/zen-avatar-icon/zen-avatar-icon.stories.mdx
- src/components/zen-button/zen-button.stories.mdx
- src/components/zen-card/zen-card.stories.mdx
- src/components/zen-checkbox/zen-checkbox.stories.mdx
- src/components/zen-form-group/zen-form-group.stories.mdx
- src/components/zen-icon/zen-icon.stories.mdx
- src/components/zen-input/zen-input.stories.mdx
- src/components/zen-menu-item/zen-option.stories.mdx
- src/components/zen-notification/zen-notification.stories.mdx
- src/components/zen-progress-tracker/zen-progress-tracker.stories.mdx
- src/components/zen-spinner/zen-spinner.stories.mdx
- src/components/zen-table/zen-table.stories.mdx
- src/components/zen-text/zen-text.stories.mdx
- src/components/zen-textarea/zen-textarea.stories.mdx
- src/components/zen-tooltip/zen-tooltip.stories.mdx
**To reproduce:**
**Bug**
Even if enterToTab is `false`, pressing `enter` key will still move focus to the next control.
**Expected**
Nothing should happen on pressing `enter`
**Reason**
If prop is set to false, we're internally set it to `null` in the spreadArgs function. This means it won't render the attribute. It's expected behaviour most of the time: If we want normal text, we just say `<zen-text />`. if we want bold text, we say `<zen-text bold />`. Being obliged to always write `<zen-text bold="false" />` is tedious.
But with props that are `true` by default we shouldn't do that. It's expected that user will explicitly have to turn it off by saying just that: `<zen-input tab-to-enter="false" />`. If he says just `<zen-input />`, `tabToEnter` will default to `true`. And this is what …
> QUICKFIX: input's prop enterToTab can't be set to false from storybook

- src/components/zen-tooltip/zen-tooltip.tsx
- src/componets-smart/zen-avatar-group/readme.md
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1155)
- Fixed that arrow is displayed based on the parameter
- Fixed that arrow is shown by setting param to be reflective
> PLAT-1155: Fix tooltip arrow show

- src/components/zen-table-header/zen-table-header.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1141)
Funny how rendering works...
Before:
After:
> PLAT-1141: Fix issue in Firefox with header border displayed on bottom of table as well

- .circleci/config.yml
- cypress.json
- package.json
I have added the Circle CI env variable CYPRESS_RECORD_KEY so we can record test runs on the cypress dashboard and use the cypress built-in parallel run. Latter when we will have more E2E tests to run and not enough space for recording  I will make a parallel run using the Circle CI only and different reported where we can follow the test statistics etc. But for now we have a cypress dashboard for that.  
[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines …
> VRT: Enable parallel runs for VRT tests

- src/components/zen-tooltip/zen-tooltip.tsx
[jira](https://reciprocitylabs.atlassian.net/browse/PLAT-1122)
Problem was that mouse-out happened only on the trigger element and tooltip parent element. If some child element (like some span inside tooltip), was touching the edge of the tooltip, mouse-out occurred only on this child span and not on tooltip parent (because mouse never hovered over it).
fix: mouse-out is also listened on children elements
> PLAT-1122: ZenUI Tooltip does not hide

- src/components/zen-avatar-icon/zen-avatar-icon.tsx
- src/stories/components/docs-table/docs-table.tsx
- src/stories/components/html-playground/html-playground.tsx
PR addresses these warnings when linting the code:
```
% yarn lint
yarn run v1.22.4
$ eslint --fix --ext .js,.ts,.tsx src/
/Users/mplesec/Workspace/reciprocity/zen-ui/src/components/zen-avatar-icon/zen-avatar-icon.tsx
52:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
/Users/mplesec/Workspace/reciprocity/zen-ui/src/stories/components/docs-table/docs-table.tsx
15:23  warning  Argument 'docTag' should be typed  @typescript-eslint/explicit-module-boundary-types
/Users/mplesec/Workspace/reciprocity/zen-ui/src/stories/components/html-playground/html-playground.tsx
6:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
✖ 3 problems (0 errors, 3 warnings)
✨  Done in 5.57s.
```
[Zen UI …
> QUICK-FIX: Add missing typings

- src/components/zen-avatar/zen-avatar.scss
- src/components/zen-avatar/zen-avatar.stories.mdx
- src/components/zen-avatar/zen-avatar.tsx
- src/components/zen-tooltip/zen-tooltip.scss
- src/components/zen-tooltip/zen-tooltip.tsx
- src/componets-smart/zen-avatar-group/readme.md
- src/zen-styles/mixins/helpers.scss
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1194)
- I removed the tooltip default padding like we discussed with Jan. Components should not have it right. Please notify the app team this will change the tooltip content.
- And Jan i fixed a minor issue in tooltip with setting the shown time for scrollable content. Hope its ok.
- Also updated to use zen ui components
> PLAT-1194: Fix avatar group firefox display issues

- src/components/zen-tooltip/zen-tooltip.tsx
- the problem was that mousemove doesn't occur if mouse is stall and content underneath mouse pointer is scrolled
> PLAT-1223: Tooltip on scroll content hides the tooltip

- src/components/zen-dropdown/zen-dropdown.tsx
PR adds the name attribute, since it's the default way for referencing this element in forms. See: https://www.w3schools.com/tags/tag_select.asp
> QUICK-FIX: Add name attribute to ZenDropdown

- src/components.d.ts
- src/components/zen-progress-tracker/zen-progress-tracker.scss
- src/components/zen-progress-tracker/zen-progress-tracker.spec.tsx
- src/components/zen-progress-tracker/zen-progress-tracker.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1242)
It was agreed by designers that labels should be 8rem. I’m now exposing a new prop labelWidth that allows you to override this default value if needed.
> PLAT-1242: Increase the width of the progress tracker labels

- src/components/zen-avatar-group/zen-avatar-group.scss
Noticed this when using it in ZenComply.
https://user-images.githubusercontent.com/9392804/110458360-f611a500-80cb-11eb-8263-c489b52706f4.mov
Simple CSS property change since `justify-content` is used for aligning items when direction is horizontal.
> QUICK-FIX: Center align ZenAvatarGroup children

- package.json
- yarn.lock
Not entirely sure why this happens, but an update to the lock file is needed. I'm guessing since dependencies are not pinned to the exact version.
Update: Babel updated their core package today.
So what likely happened is that the `@babel/preset-typescript` package was a dependency of the previous version and not the new one. Since dependencies aren't pinned it didn't get this dependency anymore. Coupled with some caching stuff locally and/or on CI and we had these problems blocking the build.
[Git commit …
> QUICK-FIX: Update lock file

- src/components.d.ts
- src/components/zen-table-header/zen-table-header.scss
- src/components/zen-table-header/zen-table-header.stories.mdx
- src/components/zen-table-header/zen-table-header.tsx
- src/components/zen-table-row/zen-table-row.scss
- src/components/zen-table-row/zen-table-row.tsx
- src/components/zen-table/zen-table.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1461)
- Added additionally indeterminate state for the tree parent rows.
- Regarding implementation a lot of room for improvement. To many loops! Will try improve it in upcoming prs.
- Test will be added here https://reciprocitylabs.atlassian.net/browse/PLAT-1537 to improve coverage.
> PLAT-1461: Add indeterminate state

- src/components/zen-progress-tracker/zen-progress-tracker.tsx
[PLAT-1491: Progress tracker not sending information on the "change" event - JIRA](https://reciprocitylabs.atlassian.net/browse/PLAT-1491)
Hey! This is a draft because I didn't remove the "internal state" (`internalActiveIndex`) because it seems to be tied to the "items state", and when removed, only 2 out of 3 steps would trigger the event (:P)... I'm sure I was missing some context there, so I went with just mutating the prop and leave the method that watches the prop update the internal one.
By mutating the value, I didn't need to add a custom event, as the implementation can check the `target.activeIndex`.
> PLAT-1491: Reflect the change of the progress tracker active index

- .husky/pre-commit
- .lintstagedrc
- package.json
No Jira - Follow-up fix for #254 - We were trying to format EVERYTHING with ESLint, so I changed the config of `lint-staged` so non-t/js files are only parsed by Prettier.
@chavlji The reason #255 is failing it's because one of the files is missing Prettier formatting. You can run `yarn format src/` to fix it.
> QUICKFIX: re-enable lint-staged

- src/components/zen-date-picker/zen-date-picker.tsx
- picker was reopened because of input.focus. Focusing input after click isn't needed anyway.
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1601)
> PLAT-1601: Date picker is not closed properly if user type the date

- .circleci/config.yml
This is not due to an error (yet): in order to deploy the storybook, we first need the changelog to be updated, so the `deploy` step must depend on the `publish` step.
The `publish` step already depends on `build`, so the files should be there.
> QUICKFIX: require publish before deploy on CircleCI

- .circleci/config.yml
- .releaserc
- Now that we know that the deploy works, I re-enabled NPM deploys.
- Instead of generating the Storybook on the `build` step, since it needs to be updated after `semantic-release`, I moved it to the `publish` step and made the `build` step run only Stencil.
> Yes, the commit to enable NPM should be a `chore:`, but I want to trigger a release, that's why I used `fix:`.
> QUICKFIX: Enable NPM && Fix Storybook deploy

- .storybook/preview.scss
Fix storybook overlapping dropdown:
Also pushed commit that should be pushed in [this pr](https://github.com/reciprocity/zen-ui/pull/280):
When I set menu width to 50% the size of menu is not correct.
> QUICK: Fix Firefox storybook overlapping

- src/components/zen-drawer/zen-drawer.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1780)
> PLAT-1780: When zen-drawer is not opened on first load display is set to none

- .circleci/config.yml
Enabling the React bindings should be a 'chore', but we need to actually trigger a release, that's why it's a 'fix'.
> Re-enable React bindings deploy

- .husky/pre-push
- cypress/tsconfig.json
- package.json
- src/.eslintrc.js
- src/components/helpers/jest.ts
- src/components/helpers/tests/animations.spec.tsx
- src/components/zen-animate/test/zen-animate.spec.tsx
- src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx
- src/components/zen-breadcrumbs/test/zen-breadcrumbs.spec.tsx
- src/components/zen-date-picker/tests/date-helpers.spec.ts
- src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
- src/components/zen-dropdown/test/zen-dropdown.spec.tsx
- src/components/zen-input/test/zen-input.spec.tsx
- src/components/zen-modal/test/zen-modal.spec.tsx
- src/components/zen-modal/test/zen-modals-service.spec.tsx
- src/components/zen-notification/test/zen-notification.spec.tsx
- src/components/zen-panel/test/zen-panel.spec.tsx
- src/components/zen-popover/test/zen-popover.spec.tsx
- src/components/zen-table-row/test/zen-table-row.spec.tsx
- src/components/zen-table/test/zen-table.spec.tsx
- src/components/zen-tooltip/test/zen-tooltip.spec.tsx
- tsconfig.json
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1800)
- The main `tsconfig` now uses the jest types, and on the `cypress` directory there's a new `tsconfig` that extends the one on the root, with the types for cypress.
- I fixed all the type errors and most of the mock implementations on the unit tests; the reason I also changed the mocks it's because most of the type issues were related to that.
- I added a new `typecheck` script to the `package.json` and hooked it on the `pre-push`, like `mf-execution`.
- Yes, the commits are really small in some cases, and it's possible that I could've used one commit for each type of change, but I actually did the changes one component at a time, based on the `tsc` report. I also considered that it could be beneficial to have these …
> PLAT-1800: Fix types on the tests

- src/components/zen-date-picker/zen-date-picker.tsx
Bug:
Zen-date-picker: If attr `formatted-date` is set to same date as today, value isn't initialized and calendar is empty:
> QUICK: Bugfix - Date picker - empty if formattedDate === today

- package.json
- src/components.d.ts
- src/components/zen-card/zen-card.tsx
- src/components/zen-checkbox/zen-checkbox.tsx
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-drawer/zen-drawer.tsx
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-input/zen-input.tsx
- src/components/zen-modal/zen-modal.tsx
- src/components/zen-radio/zen-radio.tsx
- src/components/zen-text/zen-text.tsx
- src/components/zen-textarea/zen-textarea.tsx
- src/components/zen-toggle/zen-toggle.tsx
- src/interface.d.ts
- src/stories/components/html-playground/html-playground.tsx
> I didn't assign anyone because it was friday night; If you are reviewing this on monday morning and there's no one assigned, please add the missing reviewers, thanks!
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1977)
It copies the implementation of [Ionic core repository](https://github.com/ionic-team/ionic-framework/tree/master/core) for publishing helper types.
With this change, implementation can import types like `AvatarData` directly from `@reciprocity/zen-ui`:
```diff
- import { AvatarData } from '@reciprocity/zen-ui/dist/types/components/helpers/types';
+ import { AvatarData } from '@reciprocity/zen-ui';
```
Since this PR was so small (the first commit), I took the opportunity and added all the missing type annotations for components props; apparently, if a …
> PLAT-1977: Export helper types & add missing annotations

- src/components/helpers/helpers.ts
- src/components/helpers/types.ts
- src/components/zen-avatar-details/zen-avatar-details.tsx
- src/components/zen-avatar-group/zen-avatar-group.tsx
- src/components/zen-avatar/zen-avatar.tsx
- src/components/zen-button/zen-button.tsx
- src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
- src/components/zen-date-picker/zen-date-picker.tsx
- src/components/zen-dropdown/zen-dropdown.tsx
- src/components/zen-input/zen-input.tsx
- src/components/zen-tooltip/zen-tooltip.tsx
The original scope of this branch was to be a follow up for #330 and add a new type of `EventEmitter` that would allow us to specific the `event.target` from the component itself:
```ts
export interface ZenCustomEvent<E extends EventTarget = EventTarget, T = void> extends CustomEvent<T> {
target: E;
}
export interface ZenEventEmitter<E extends EventTarget = EventTarget, T = void> {
emit: (data?: T) => ZenCustomEvent<E, T>;
}
// ZenEventEmitter<HTMLZenCheckboxElement>
// That would type `event.target` as the checkbox without the need to re cast it to access its `value` prop.
```
It looks wonderful, and it works inside `zen-ui`, but... Stencil ignores it when generating the `components.d.ts` 😭 - so, no way to use.
But why did I create a PR? Well, while working on these types, I found out …
> Properly type props of components used within other components

- src/components.d.ts
- src/components/zen-sidebar-nav/zen-sidebar-nav.scss
- src/components/zen-sidebar-nav/zen-sidebar-nav.stories.mdx
- src/components/zen-sidebar-nav/zen-sidebar-nav.tsx
- src/components/zen-sidebar/zen-sidebar.tsx
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2069)
- There is a strange issue when collapsing the sidebar. The collapsed width is not correct. @f-jauregui would you be so good to check this? Cant find what is the issue here.
> PLAT-2069: Fix sidebar nav width issue

- src/components/zen-sidebar-nav-item/zen-sidebar-nav-item.tsx
- event handler should be prefixed by `zen` prefix
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2080)
> PLAT-2080: Sidebar navigation > submenu options are not deselected when choosing other option

- src/components/helpers/helpers.ts
- src/components/zen-status-tracker/zen-status-tracker.tsx
- setAttribute always triggers observer callback.
- added a check to set it only if it actually differs.
[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2101)
Takeaway:
Always test observers by mutating children in manually from the dev tools.
To discuss:
Could we add unit tests to test such behaviour?
> PLAT-2101: Bug: Status tracker observer loops infinitely

- src/components/zen-tooltip/zen-tooltip.tsx
This came from the demo feedback.
> QUICKFIX: Make tooltip link open on a new tab

- src/components/zen-notification/zen-notification.scss
- src/components/zen-notification/zen-notification.tsx
ZenText was overlapping the close icon for the Notification component. This change fixes that by including the close button inside the ZenSpace and updating it a bit with the styling.
> QUICKFIX(zen-notification): Update close icon position

- src/components/zen-notifications-wrapper/zen-notifications-wrapper.tsx
Marko needs to insert link into notification:
> QUICK: zen-notification - Set inner html instead of text
